# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.0"
manifest_format = "2.0"
project_hash = "18c1d4fc651b6386a05f02388bde98e99764c57f"

[[deps.JuliaSyntax]]
deps = ["Mmap"]
git-tree-sha1 = "bf799a0c18ff9126866761da7ffce2bbc1d59995"
uuid = "70703baa-626e-46a2-a12c-08ffd08c73b4"
version = "0.1.0"

[[deps.JuliaSyntaxCore]]
deps = ["JuliaSyntax"]
path = "JuliaSyntaxCore"
uuid = "fcbcd6f9-6e0c-440f-a208-7b935ba62d67"
version = "0.1.0"

[[deps.Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"
