# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.3"
manifest_format = "2.0"

[[deps.JuliaSyntax]]
deps = ["Mmap"]
git-tree-sha1 = "44cfaf2d61bc7a9f2ae2cd6326e3e500d64bb07c"
repo-rev = "main"
repo-url = "https://github.com/JuliaLang/JuliaSyntax.jl"
uuid = "70703baa-626e-46a2-a12c-08ffd08c73b4"
version = "0.1.0"

[[deps.JuliaSyntaxCore]]
deps = ["JuliaSyntax"]
git-tree-sha1 = "d4a9cf1e3f2220deb3bffdc7e7ef98fc4bf31702"
repo-rev = "main"
repo-subdir = "sysimage/JuliaSyntaxCore"
repo-url = "https://github.com/JuliaLang/JuliaSyntax.jl"
uuid = "05e5f68f-ccd0-4d84-a81a-f557a333a331"
version = "0.1.0"

[[deps.Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"
