# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.5"
manifest_format = "2.0"
project_hash = "18c1d4fc651b6386a05f02388bde98e99764c57f"

[[deps.JuliaSyntax]]
git-tree-sha1 = "e00e2b013f3bd98d3789f889b9305c1546ecd1ab"
uuid = "70703baa-626e-46a2-a12c-08ffd08c73b4"
version = "0.4.8"

[[deps.JuliaSyntaxCore]]
deps = ["JuliaSyntax"]
path = "JuliaSyntaxCore"
uuid = "fcbcd6f9-6e0c-440f-a208-7b935ba62d67"
version = "0.1.0"
